apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "5"
      deployment.kubernetes.io/max-replicas: "7"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-03-21T18:31:26Z"
    generation: 1
    labels:
      app: webapp
      pod-template-hash: 77d49cc4b9
    name: webapp-77d49cc4b9
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: webapp
      uid: 144e2a21-5252-47fb-bf85-23d89f6afd35
    resourceVersion: "38923"
    uid: 7d6823ce-894c-4188-b46f-6048e0ef0161
  spec:
    replicas: 5
    selector:
      matchLabels:
        app: webapp
        pod-template-hash: 77d49cc4b9
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: webapp
          pod-template-hash: 77d49cc4b9
      spec:
        containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 5
    fullyLabeledReplicas: 5
    observedGeneration: 1
    readyReplicas: 5
    replicas: 5
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
