apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  labels:
    tier: msg
spec:
  selector:
    tier: msg
    type: ClusterIP
  ports:          
    - name: messaging-service
      protocol: TCP
      port: 6379
      targetPort: 6379
