apiVersion: v1
kind: Namespace
metadata:
  name: finance-oshri
  labels: 
    name: finance-oshri
---
apiVersion: v1
kind: Pod
metadata:
  name: temp-bus
  namespace: finance-oshri
spec:
  containers:
  - name: temp-bus
    image: redis:alpine
