apiVersion: v1
kind: Pod
metadata:
  name: use-pvspec-oshri
  creationTimestamp: null
  labels:
    run: use-pv  
spec:
  containers:
    - name: use-pv
      image: nginx
      resources: {}            
      volumeMounts:
        - mountPath: "/data"
          name: nginx-mnt
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: nginx-mnt
    persistentVolumeClaim:
      claimName: pvc-1
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: pv-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  storageClassName: default
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"



