apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: alpha
    image: nginx
    env:
    - name: alpha_env_var_name
      value: "alpha-env-var-value"
  - name: beta
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "echo running sleep; sleep 4800"]
    env:
    - name: beta_env_var_name
      value: "beta-env-var-value"
